apiVersion: batch/v1
kind: CronJob
metadata:
  name: nginx-cronjob-backup
  namespace: nginx
spec:
  schedule: "* * * * *"   # runs every minute
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: nginx-cronjob-backup
        spec:
          containers:
          - name: nginx-cronjob-pod
            image: busybox:latest
            command:
            - sh
            - -c
            - |
              echo "Backup Started"
              mkdir -p /demo-data
              mkdir -p /backups
              cp -r /demo-data/ /backups/
              echo "Backup Completed"
            volumeMounts:
            - name: data-volume
              mountPath: /demo-data
            - name: backup-volume
              mountPath: /backups

          restartPolicy: OnFailure

          volumes:
           - name: data-volume
             hostPath:
               path: /demo-data
               type: DirectoryOrCreate
           - name: backup-volume
             hostPath:
               path: /backups
               type: DirectoryOrCreate
