kind: CronJob
apiVersion: batch/v1
metadata:
 name: nginx-cronjob-backup
 namespace: nginx
spec:
  schedule: "* * * * *"  
  jobTemplate:
    spec:
       template: 
          metadata:
            name: nginx-cronjob-backup
           labels:
             app: nginx-cronjob-backup
        spec: 
         containers: 
         - name: nginx-cronjob-pod
           image: busybox:latest
           command:
           - sh
           - -c
           - >
             echo "Backup Started"
             mkdir -p /backups &&
             mkdir -p /demo-data &&
             cp -r /demo-data /backups &&
             echo "Backup Completed" ;
         volumeMounts:
              - name: data-volume
                mountPath: /demo-data
              - name: backup-volume
                mountPath: /backups
        restartPolicy: OnFailure
        volumes:
         - name: data-volume
           hostPath: 
             path: /demo-data
             type: DirectoryOrCreate
         - name: data-volume
           hostPath:
              path:  /backups
              type: DirectoryOrCreate
              

           
