kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-pv
  namespace: nginx
spec: 
  capacity:
     storage: 1Gi
  accessModes:
     - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage-pv
  hostPath:
    path: /mnt/data